---
#- hosts: pi1
#  tasks:
#  - name: Set hostname
#    become: yes
#    hostname:
#      name: pi1

- hosts: pi4
  tasks:
  - name: Set hostname
    become: yes
    hostname:
      name: pi4

- hosts: pi4s
  tasks:
  - name: Set hostname
    become: yes
    hostname:
      name: pi4s

- hosts: server
  tasks:
  - name: Get latest snapcast release
    uri:
      url: https://api.github.com/repos/badaix/snapcast/releases/latest
      return_content: true
    register: json_reponse
  - name: Download snapserver
    get_url:
      url: "{{ json_reponse.json.assets.4.browser_download_url }}"
      dest: /tmp/snapserver-latest.tar.gz
  - name: ensure snapserver is updated
    become: yes
    apt:
      deb: /tmp/snapserver-latest.tar.gz
  - name: Prepare raspotify installation
    become: yes
    apt:
      pkg:
      - curl
      - apt-transport-https
  - name: Add raspotify repository signing key
    become: yes
    apt_key:
      url: https://dtcooper.github.io/raspotify/key.asc
      state: present
  - name: Enable raspotify repository
    become: yes
    apt_repository:
      repo: deb https://dtcooper.github.io/raspotify raspotify main
      state: present

  - name: Install raspotify
    become: yes
    apt:
      update_cache: yes
      pkg:
      - raspotify

  - name: Configure raspotify
    become: yes
    blockinfile:
      path: "/etc/raspotify/conf"
      block: |
        LIBRESPOT_BACKEND="pipe"
        LIBRESPOT_DEVICE="/tmp/snapfifo"

  - name: Configure raspotify service to share /tmp with snapserver
    become: yes
    blockinfile:
      path: "/etc/systemd/system/raspotify.service.d/ShareTmp.conf"
      block: |
        [Unit]
        JoinsNamespaceOf=snapserver.service

  - name: Restart raspotify
    become: yes
    service:
      name: raspotify
      state: restarted
      enabled: yes
      daemon_reload: yes

  - name: Configure snapserver
    become: yes
    copy:
      content: "stream = pipe:///tmp/snapfifo?name=Spotify&mode=read"
      dest: "/etc/snapserver.conf"

  - name: Configure snapserver service to share /tmp with raspotify
    become: yes
    blockinfile:
      path: "/etc/systemd/system/snapserver.service.d/ShareTmp.conf"
      block: |
        [Service]
        PrivateTmp=true
        [Unit]
        JoinsNamespaceOf=raspotify.service

  - name: Restart snapserver
    become: yes
    service:
      name: snapserver
      state: restarted
      enabled: yes
      daemon_reload: yes

- hosts: clients
  tasks:
  - name: Get latest snapcast release
    uri:
      url: https://api.github.com/repos/badaix/snapcast/releases/latest
      return_content: true
    register: json_reponse
  - name: Download snapclient
    get_url:
      url: "{{ json_reponse.json.assets.1.browser_download_url }}"
      dest: /tmp/snapclient-latest.tar.gz
  - name: ensure snapclient is updated
    become: yes
    apt:
      deb: /tmp/snapclient-latest.tar.gz
  - name: Restart snapclient
    become: yes
    service:
      name: snapclient
      state: restarted
      enabled: yes

- hosts: clients:!server
  tasks:
  - name: Make sure raspotify is not running
    become: yes
    service:
      name: raspotify
      state: stopped
      enabled: no
  - name: Make sure snapserver is not running
    become: yes
    service:
      name: snapserver
      state: stopped
      enabled: no

