---
#- hosts: pi1
#  tasks:
#  - name: Set hostname
#    become: yes
#    hostname:
#      name: pi1

- hosts: pi4
  tasks:
  - name: Set hostname
    become: yes
    hostname:
      name: pi4

- hosts: pi4s
  tasks:
  - name: Set hostname
    become: yes
    hostname:
      name: pi4s

- hosts: all
  tasks:
  - name: Remove needless packages
    become: yes
    package:
      state: absent
      name:
        - chromium-browser
        - firefox
        - vlc

- hosts: server
  tasks:
  - name: Get latest snapcast release
    uri:
      url: https://api.github.com/repos/badaix/snapcast/releases/latest
      return_content: true
    register: json_response

  - name: Find the link to download server package
    set_fact:
      download_url: "{{ item.browser_download_url }}"
    when: item.name | regex_search('snapserver.*arm64-bookworm.deb')
    loop: "{{ json_response.json.assets }}"

  - name: Download snapserver
    get_url:
      url: "{{ download_url }}"
      dest: /tmp/snapserver-latest.deb

  - name: ensure snapserver is updated
    become: yes
    apt:
      deb: /tmp/snapserver-latest.deb

  - name: Prepare raspotify installation
    become: yes
    apt:
      pkg:
      - curl
      - apt-transport-https

  - name: Add raspotify repository signing key
    become: yes
    get_url:
      url: https://dtcooper.github.io/raspotify/key.asc
      dest: /usr/share/keyrings/raspotify_key.asc
      mode: '0644'
      owner: 'root'

  - name: Enable raspotify repository
    become: yes
    apt_repository:
      repo: deb [signed-by=/usr/share/keyrings/raspotify_key.asc] https://dtcooper.github.io/raspotify raspotify main
      state: present

  - name: Install raspotify
    become: yes
    apt:
      update_cache: yes
      pkg:
      - raspotify

  - name: Disable raspotify
    become: yes
    service:
      name: raspotify
      state: stopped
      enabled: false

  - name: Configure snapserver
    become: yes
    copy:
      content: |
        [stream]
        source = spotify:///usr/bin/librespot?name=Spotify&devicename=RPi4s
      dest: "/etc/snapserver.conf"

  - name: Restart snapserver
    become: yes
    service:
      name: snapserver
      state: restarted
      enabled: yes
      daemon_reload: yes

- hosts: clients
  tasks:
  - name: Get latest snapcast release
    uri:
      url: https://api.github.com/repos/badaix/snapcast/releases/latest
      return_content: true
    register: json_response

  - name: Find the link to download client package
    set_fact:
      download_url: "{{ item.browser_download_url }}"
    when: item.name | regex_search('snapclient.*arm64-bookworm.deb')
    loop: "{{ json_response.json.assets }}"

  - name: Download snapclient
    get_url:
      url: "{{ download_url }}"
      dest: /tmp/snapclient-latest.deb

  - name: ensure snapclient is updated
    become: yes
    apt:
      deb: /tmp/snapclient-latest.deb

  - name: Restart snapclient
    become: yes
    service:
      name: snapclient
      state: restarted
      enabled: yes

- hosts: clients:!server
  tasks:
  - name: Make sure raspotify is not running
    become: yes
    service:
      name: raspotify
      state: stopped
      enabled: no

  - name: Make sure snapserver is not running
    become: yes
    service:
      name: snapserver
      state: stopped
      enabled: no
